apiVersion: v2
name: raw
version: 0.1.0
appVersion: 0.1.0
description: Copy of incubator/raw - A place for all the Kubernetes resources which don't already have a home.
maintainers:
  - name: sebastiangaiser
