{{- if ne .Values.vaultwarden.adminToken.value "disabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vaultwarden.fullname" . }}-admin-token
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.vaultwarden.adminToken.value "generated" }}
  admin-token: {{ randAlphaNum 48  | b64enc | quote }}
  {{- else }}
  admin-token: {{ .Values.vaultwarden.adminToken.value | b64enc | quote }}
  {{- end }}
{{- end }}
