{{- if .Values.horizontalAutoscaling.enabled -}}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vaultwarden.fullname" . }}
  minReplicas: {{ .Values.horizontalAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.horizontalAutoscaling.maxReplicas }}
  metrics:
    {{- if .Values.horizontalAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalAutoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.horizontalAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalAutoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end -}}
