{{- if .Values.vertical_autoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "vaultwarden.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vertical_autoscaling.updateMode }}
{{- end }}
