# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - postgres-operator-charts=https://opensource.zalando.com/postgres-operator/charts/postgres-operator
helm-extra-args: --timeout 600s
