repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.1
    hooks:
      - id: helm-docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
#      - id: check-yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
