---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capacitor.fullname" . }}
  labels:
    {{- include "capacitor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.k8s.io
      - apps
      - ""
    resources:
      - pods
      {{- if .Values.capacitor.showPodLogs }}
      - pods/log
      {{- end }}
      - ingresses
      - deployments
      - services
      {{- if .Values.capacitor.showEvents }}
      - events
      {{- end }}
      - configmaps
      {{- if .Values.capacitor.showSecrets }}
      - secrets
      {{- end }}
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - infra.contrib.fluxcd.io
    resources:
      - gitrepositories
      - ocirepositories
      - buckets
      - helmrepositories
      - helmcharts
      - kustomizations
      - helmreleases
      - terraforms
    verbs:
      - get
      - watch
      - list
      {{- if not .Values.capacitor.readonly }}
      - patch # to allow force reconciling by adding an annotation
      {{- end }}
