{{- if and .Values.networkPolicy.enabled (eq .Values.networkPolicy.flavor "kubernetes") -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "capacitor.fullname" . }}-ingress
  namespace: {{ template "capacitor.namespace" . }}
  labels:
    {{- include "capacitor.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
  podSelector:
    matchLabels:
      {{- include "capacitor.selectorLabels" . | nindent 6 }}
{{- end -}}
