---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capacitor.serviceAccountName" . }}
  namespace: {{ template "capacitor.namespace" . }}
  labels:
    {{- include "capacitor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
