---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "capacitor.fullname" . }}
  labels:
    {{- include "capacitor.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
    annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "capacitor.selectorLabels" . | nindent 4 }}
