# Default values for vaultwarden.

replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  tag: "1.25.0-alpine"

vaultwarden:
  environment: "production"
  rocketPort: 8080
  adminToken:
    # -- possible values are 'generated', 'disabled' or any specific value
    value: "disabled"
  extraEnvironmentVars: {}
#    DOMAIN: "https://bitwarden.example.com"
#    SIGNUPS_ALLOWED: false
#    SIGNUPS_VERIFY: false
#    EXTENDED_LOGGING: true
#    LOG_LEVEL: "info"

initContainers: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80

## persistent volume
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  # subPath:
  # storageClass:
  # existingClaim: "vaultwarden-pvc"

additionalVolumeMounts: []
additionalVolumes: {}

postgresql:
  enabled: false
  version: "14"
  instances: 1
  size: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi
  additionalConfiguration: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: vaultwarden.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: vaultwarden-tls
  #    hosts:
  #      - vaultwarden.example.com

livenessProbe:
  httpGet:
    path: /api/alive
    port: http

readinessProbe:
  httpGet:
    path: /api/alive
    port: http

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 200m
  #   memory: 256Mi

horizontalAutoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

verticalAutoscaling:
  enabled: false
  updateMode: "Off"

nodeSelector: {}

tolerations: []

affinity: {}
