# Default values for Vaultwarden.

replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  tag: "1.27.0-alpine"

# -- Vaultwarden specific configuration
vaultwarden:
  environment: "production"
  rocketPort: 8080
  adminToken:
    # -- Possible values are 'generated', 'disabled' or any specific value
    value: "disabled"
  # -- Additional environment variables
  extraEnvironmentVars: {}
#    DOMAIN: "https://bitwarden.example.com"
#    SIGNUPS_ALLOWED: false
#    SIGNUPS_VERIFY: false
#    EXTENDED_LOGGING: true
#    LOG_LEVEL: "info"

# -- Init-containers
initContainers: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL

# -- Service
service:
  type: ClusterIP
  port: 80

# -- Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  hosts:
    - host: vaultwarden.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: vaultwarden-tls
  #    hosts:
  #      - vaultwarden.example.com

# -- Persistent volume
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  # subPath:
  # storageClass:
  # existingClaim: "vaultwarden-pvc"

# -- Additional volume mounts
additionalVolumeMounts: []
# -- Additional volumes
additionalVolumes: {}

# -- Liveness probe
livenessProbe:
  httpGet:
    path: /api/alive
    port: http

# -- Readiness probe
readinessProbe:
  httpGet:
    path: /api/alive
    port: http

# -- Resources
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 200m
#   memory: 256Mi

# -- Node selectors
nodeSelector: {}
# -- Toleration's
tolerations: []
# -- Affinities
affinity: {}

## -- Zalando PostgreSQL database configuration
postgresql:
  enabled: false
  version: "14"
  instances: 1
  size: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi
  additionalConfiguration: {}

# -- HPA configuration
horizontalAutoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

# -- VPA configuration
verticalAutoscaling:
  enabled: false
  updateMode: "Off"

# -- PodDisruptionBudget configuration
podDisruptionBudget:
  enabled: false
#  minAvailable: 1
#  maxUnavailable: 1
