name: EditorConfig Checker

on:
  push:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
