name: Helm docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write # for git push

    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Check Docs
        run: |
          docker run --rm --pull always --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:latest
          if ! git diff --exit-code; then
              echo "Documentation was not up to date. Adding changes for helm-docs and commited/pushed changes!" >&2
              find . -name '*.md' | xargs git add
              git commit --signoff -m "Sync README from main"
              git push
          fi
